# Generated by Django 4.2.5 on 2023-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_pupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='gender',
            field=models.CharField(default='м', max_length=1),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='class_p',
            field=models.CharField(max_length=3),
        ),
    ]
