# Generated by Django 4.2.5 on 2023-11-30 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_like_books_pupil_bithday_pupil_coming_of_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like_books',
            old_name='name_Book',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='pupil',
            name='bithday',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 16, 42, 22, 85070, tzinfo=datetime.timezone.utc)),
        ),
    ]
