# Generated by Django 4.2.5 on 2023-11-30 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_rename_name_book_like_books_name_alter_pupil_bithday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='bithday',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 16, 46, 59, 968821, tzinfo=datetime.timezone.utc)),
        ),
    ]
