# Generated by Django 4.2.5 on 2024-03-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_alter_pupil_bithday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like_books',
            options={'verbose_name': 'любимые книги', 'verbose_name_plural': 'любимые книги'},
        ),
        migrations.AlterField(
            model_name='pupil',
            name='bithday',
            field=models.DateTimeField(blank=True),
        ),
    ]
